
version: '3.8'

services:
  test_app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    

  postgres_db:
    image: postgres:14
    environment:
       POSTGRES_USER: "arun"
       POSTGRES_PASSWORD: "root"
       POSTGRES_DB : "test_docker"
    ports:
      - "5432:5432"
    volumes:
      - db_storage:/var/lib/postgres/data

volumes:
  db_storage: