/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.checkerframework.checker.units.qual.A;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testAdd(){
        App app = new App();
        int expected = 3;
        int actual = app.addTwo(1,2);
        assertEquals(expected , actual);
    }
}
